# Generated by Django 4.2.30 on 2026-08-17 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dob_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_notification'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_delivery_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('delivery_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='delivery.deliveryassignment')),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.deliveryboyprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_feedback', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
