# Generated by Django 4.2.30 on 2026-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
