# Generated by Django 4.2.30 on 2026-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryassignment_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Central Kitchen Hub (Kochi)', max_length=120)),
                ('address', models.CharField(default='MG Road / Central Hub, Ernakulam, Kerala', max_length=255)),
                ('latitude', models.FloatField(default=9.9816)),
                ('longitude', models.FloatField(default=76.2999)),
                ('max_delivery_radius_km', models.FloatField(default=15.0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Service Area Setting',
                'verbose_name_plural': 'Delivery Service Area Settings',
            },
        ),
    ]
