# Generated by Django 4.2.30 on 2026-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysetting',
            name='address',
            field=models.CharField(default='Kanjirappally Town, Kottayam, Kerala', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='latitude',
            field=models.FloatField(default=9.5564),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='longitude',
            field=models.FloatField(default=76.7909),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='max_delivery_radius_km',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='name',
            field=models.CharField(default='Central Kitchen Hub (Kanjirappally)', max_length=120),
        ),
    ]
