# Generated by Django 4.2.30 on 2026-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dob_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
