# Generated by Django 4.2.30 on 2026-08-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryboyprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
