# Generated by Django 4.2.30 on 2026-08-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('busy', 'On Delivery'), ('offline', 'Offline')], db_index=True, default='available', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('chef', 'Chef'), ('staff', 'Staff'), ('delivery_boy', 'Delivery Boy'), ('admin', 'Administrator')], db_index=True, default='customer', max_length=20),
        ),
    ]
