# Generated by Django 4.2.30 on 2026-09-01 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work / Office'), ('parents', "Parent's House"), ('landmark', 'Nearby Landmark / Junction'), ('other', 'Other')], default='home', max_length=20)),
                ('description', models.TextField(blank=True, help_text='House name, building, street, or flat number', null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearby shop, temple, church, hospital, or bus stop', max_length=150, null=True)),
                ('latitude', models.FloatField(default=9.462534)),
                ('longitude', models.FloatField(default=76.72185)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
