# Generated by Django 4.2.30 on 2026-07-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('score', models.FloatField(default=1.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_cholesterol', models.BooleanField(default=False)),
                ('has_bp', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated values, e.g. peanuts, dairy', null=True)),
                ('dietary_preference', models.CharField(choices=[('any', 'No Preference'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto-Friendly')], default='any', max_length=20)),
                ('daily_calorie_target', models.FloatField(default=2000.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
