# Generated by Django 4.2.30 on 2026-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_latitude_alter_order_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_delivery_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_kitchen_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(default=9.5564),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(default=76.7909),
        ),
    ]
