# Generated by Django 4.2.30 on 2026-08-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='malayalam_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='malayalam_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
