# Generated by Django 4.2.30 on 2026-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditem_malayalam_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_food_item_name'),
        ),
    ]
