# Generated by Django 4.2.30 on 2026-09-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fooditem_unique_food_item_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fooditem',
            name='unique_food_item_name',
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(fields=('name', 'meal_session'), name='unique_food_item_name_per_session'),
        ),
    ]
